settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: flight-grpc
  path: .
  commands: 
    install:
      status: true 
      method: go build -o tmp/app main.go
    run:
      status: true
      method: tmp/app
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
